import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AccessAlarmIcon from '@mui/icons-material/AccessAlarm';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' bg-red-300'>
      <AccessAlarmIcon/>
      </div>

     
    </div>
  )
}
